//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusID { get; set; }
        public string Status1 { get; set; }
        public int Order { get; set; }
        public bool CanLogin { get; set; }
        public bool CanSearch { get; set; }
        public bool IsSuspended { get; set; }
        public bool IncludeInStats { get; set; }
    }
}
