//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberInvoice
    {
        public int SubscriberInvoiceID { get; set; }
        public int SubscriberID { get; set; }
        public string StripeInvoiceID { get; set; }
        public int Amount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
    }
}
