//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorList()
        {
            this.VendorListItems = new HashSet<VendorListItem>();
        }
    
        public int VendorListID { get; set; }
        public int UserID { get; set; }
        public int VendorID { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool ReplaceList { get; set; }
        public string Filetype { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorListItem> VendorListItems { get; set; }
    }
}
