//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorListItem
    {
        public int VendorListItemID { get; set; }
        public int VendorListID { get; set; }
        public int VendorID { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string AlternatePartNumber { get; set; }
        public string AlternatePartNumber2 { get; set; }
        public string ModelNumber { get; set; }
        public string Manufacturer { get; set; }
        public string ATAChapter { get; set; }
        public string NSN { get; set; }
        public string Aircraft { get; set; }
        public string Engine { get; set; }
        public string Cage { get; set; }
        public string NotesRemarks { get; set; }
        public string WorkShopSite { get; set; }
        public string Workscope { get; set; }
        public Nullable<bool> RepairsFrequently { get; set; }
        public Nullable<bool> PMA { get; set; }
        public Nullable<bool> DER { get; set; }
        public Nullable<bool> FreeEval { get; set; }
        public Nullable<bool> Modified { get; set; }
        public Nullable<bool> FunctionTestOnly { get; set; }
        public Nullable<bool> NoOverhaulWorkscope { get; set; }
        public Nullable<bool> CAAC { get; set; }
        public Nullable<bool> ExtendedWarranty { get; set; }
        public Nullable<bool> FlatRate { get; set; }
        public Nullable<bool> Range { get; set; }
        public Nullable<bool> NTE { get; set; }
        public string PartNumberClean { get; set; }
        public string AlternatePartNumberClean { get; set; }
        public string AlternatePartNumber2Clean { get; set; }
        public string ModelNumberClean { get; set; }
        public string NSNClean { get; set; }
        public Nullable<bool> WorkHistory { get; set; }
        public Nullable<int> Achievements { get; set; }
        public int PortalCode { get; set; }
        public string Quantity { get; set; }
        public string Condition { get; set; }
        public string Serial { get; set; }
    
        public virtual VendorList VendorList { get; set; }
    }
}
