//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.VendorLists = new HashSet<VendorList>();
        }
    
        public int VendorID { get; set; }
        public bool Active { get; set; }
        public int StatusID { get; set; }
        public bool Muted { get; set; }
        public bool Suspended { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string VendorName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string RFQEmails { get; set; }
        public string RFQPreferredMethod { get; set; }
        public string DefaultCurrency { get; set; }
        public string CompanyLogoSmall { get; set; }
        public string CompanyLogoLarge { get; set; }
        public string WebsiteURL { get; set; }
        public string Fax { get; set; }
        public string AOGPhone { get; set; }
        public string AOGEmail { get; set; }
        public string CertifyingAgenciesCerts { get; set; }
        public string LanguagesSupported { get; set; }
        public int ProfileFieldsCompleted { get; set; }
        public string RFQPhone { get; set; }
        public string RFQEmail { get; set; }
        public string RFQWebEmails { get; set; }
        public string RFQFax { get; set; }
        public Nullable<bool> OEM { get; set; }
        public Nullable<bool> OEMExclusive { get; set; }
        public Nullable<bool> OEMRequiresRMA { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PartsCount { get; set; }
        public Nullable<int> AchievementsCount { get; set; }
        public Nullable<int> WeavyCompanyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorList> VendorLists { get; set; }
    }
}
