//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorAchievementList
    {
        public int VendorAchievementListID { get; set; }
        public int VendorID { get; set; }
        public int VendorAchievementTypeID { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Filetype { get; set; }
        public bool ReplaceList { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
    }
}
