//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorSubscriberBlocked
    {
        public int VendorSubscriberBlockedID { get; set; }
        public int VendorID { get; set; }
        public int SubscriberID { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
