//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCert
    {
        public int VendorCertID { get; set; }
        public int VendorID { get; set; }
        public string Cert { get; set; }
        public string Number { get; set; }
    }
}
