//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorQuote
    {
        public int VendorQuoteID { get; set; }
        public int VendorID { get; set; }
        public Nullable<int> VendorListItemID { get; set; }
        public string PartNumber { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateResponded { get; set; }
        public Nullable<System.DateTime> DateNoQuote { get; set; }
        public Nullable<System.DateTime> DateIgnore { get; set; }
        public string Comments { get; set; }
        public string RFQID { get; set; }
        public string Currency { get; set; }
        public Nullable<int> TestPrice { get; set; }
        public Nullable<int> TestTAT { get; set; }
        public Nullable<int> RepairPrice { get; set; }
        public Nullable<int> RepairPriceRangeLow { get; set; }
        public Nullable<int> RepairPriceRangeHigh { get; set; }
        public Nullable<int> RepairTAT { get; set; }
        public Nullable<int> OverhaulPrice { get; set; }
        public Nullable<int> OverhaulPriceRangeLow { get; set; }
        public Nullable<int> OverhaulPriceRangeHigh { get; set; }
        public Nullable<int> OverhaulTAT { get; set; }
        public Nullable<int> NotToExceed { get; set; }
        public Nullable<int> RepairsFrequently { get; set; }
        public Nullable<bool> PMA { get; set; }
        public Nullable<bool> DER { get; set; }
        public Nullable<bool> FreeEval { get; set; }
        public Nullable<bool> Modified { get; set; }
        public Nullable<bool> FunctionTestOnly { get; set; }
        public Nullable<bool> NoOverhaulWorkscope { get; set; }
        public Nullable<bool> CAAC { get; set; }
        public Nullable<bool> ExtendedWarranty { get; set; }
        public Nullable<bool> FlatRate { get; set; }
        public Nullable<bool> Range { get; set; }
        public Nullable<bool> NTE { get; set; }
        public string QuoteComments { get; set; }
        public Nullable<bool> APR { get; set; }
        public Nullable<bool> FT { get; set; }
        public Nullable<bool> WorkHistory { get; set; }
        public Nullable<int> RepairPriceRange { get; set; }
        public Nullable<int> OverhaulPriceRange { get; set; }
    }
}
